### ISSUE TITLE
Team page confusion

### ISSUE THREAD

**Issue by maxwofford** [hackclub/site#1026]
This has come up in a couple calls with users and staff now so I wanted to flag that this section is confusing. People think John Abele is a board member

<img width="1223" alt="Screenshot 2023-12-07 at 14 24 52" src="https://github.com/hackclub/site/assets/5891442/e106cb36-d3c9-4c5b-ba41-4b5925a090d9">

**Comment by aramshiva** [comment]
Can this be assigned to me?

**Comment by aramshiva** [comment]
<img width="1176" alt="Screenshot 2023-12-07 at 9 01 13 PM" src="https://github.com/hackclub/site/assets/79479940/09a940c9-f1c3-411b-b8d3-e958baddd9c7">
im thinking something like this.

**Comment by maxwofford** [comment]
Nice! I think this is a good start, but screenshot feels a little unbalanced. Maybe this could be something like relabeling "our board"?

**Comment by sampoder** [comment]
"Board & Advisors”?

**Comment by grymmy** [comment]
@aramshiva do we intend on moving forward with this?

**Comment by aramshiva** [comment]
I can be unassigned
