### ISSUE TITLE
Newsletter module on main site is referencing Club Leaders newsletters for its archives

### ISSUE THREAD

**Issue by karamassie** [hackclub/site#1037]
When I click on the link to "view archives" in the main newsletter module, it's showing the archives of the Club Leaders newsletters. It'd be amazing to have the archives be the actual community newsletter

**Comment by grymmy** [comment]
Cannot reproduce this anymore - slightly old issue.  Closing this as unactionable, please reopen with link to specific page and corresponding issue if you think this was closed in error.
