### ISSUE TITLE
slack signup form button on press says "something went wrong" (though nothing is amiss)

### ISSUE THREAD

**Issue by karamassie** [hackclub/site#1041]
<img width="851" alt="Screenshot 2023-12-28 at 12 39 44 AM" src="https://github.com/hackclub/site/assets/99233707/3dd2e4cc-6cec-4138-904b-6e7af961f583">

Strangely, it DID work (as in, I got the invite email). But this will detract many people from signing up, unless they just happen to check that same email at some point.

**Comment by jaspermayone** [comment]
Yea +1 this was happening to me as well

**Comment by tobyab** [comment]
Fixed! Kara, I love your testing email.
