### ISSUE TITLE
HCB application form: prefill fields with query parameters

### ISSUE THREAD

**Issue by cjdenio** [hackclub/site#1059]
When you click "new project" to apply for a new org through the HCB dashboard, HCB sends along a few query parameters meant to prefill fields in the application form.

It looks kind of like this:

```
https://hackclub.com/hcb/apply/?userEmail=caleb%40hackclub.com
  &firstName=Caleb
  &lastName=Denio
  &returningUser=Yes%2C+I+have+used+HCB+before
  &userPhone=%2B11234567890
```

These query parameters don't currently do anything. They should!

Related to hackclub/hcb#5039

**Comment by garyhtou** [comment]
Should we move this ticket over to https://github.com/hackclub/site since the application form code is located there?

https://github.com/hackclub/site/blob/f2848ff8118720c8d9354dccaff8d973d245705c/pages/hcb/apply/index.js
