### ISSUE TITLE
hackclub.com/hcb footer links to "team@hackclub.com"

### ISSUE THREAD

**Issue by maxwofford** [hackclub/site#1062]
<img width="1188" alt="Screenshot 2024-01-17 at 16 02 52" src="https://github.com/hackclub/site/assets/5891442/2d9744b9-0d38-4ce9-8418-356849b20258">

This address should change, specifically on hackclub.com/hcb! instead of team@hackclub.com it should go to hcb@hackclub.com

**Comment by garyhtou** [comment]
https://github.com/hackclub/site/pull/1066
