### ISSUE TITLE
add a sprig-like gallery page for the Onboard site to show inspiring PCB projects made by other HCers

### ISSUE THREAD

**Issue by karamassie** [hackclub/site#1071]
Seeing other fun, visual, cool PCB projects will help new people be inspired to try to make their own designs. We also want to encourage hacks on them.

Take a lot of inspo from Sprig's and https://processing.org/ here, but with some changes and improvements!

Have them listed from new-old, but lead with a curated first row that we can change manually using filters(eg we might want to highlight some)
Make metadata for filters - some metadata will be visible/on the project and some won’t (see above note)
Need 3d renders (see @karmanyaahm who has a solution for this)
Have a way to clearly identify "has tutorial" on those that have one!

Max says “no hipster frameworks” so nonhipsters can contribute.  ideally keep it in the same codebase as /site. <<< all so it can be easily maintained.

@maxwofford pls comment if there's anything else

**Comment by karmanyaahm** [comment]
Also, I impulsively bought the domain [gerber.zip](https://gerber.zip) a while back, in case you want to host it on that LOL

**Comment by karmanyaahm** [comment]
And https://kitspace.org and [tracespace](https://tracespace.io/view/?boardUrl=https%3A%2F%2Fraw.githubusercontent.com%2Fhackclub%2FOnBoard%2F60d664c4393a6bbdf5824abd0791298e114cddb0%2Fprojects%2FKarmanyaah_Longhorn_LEDs%2Fgerber.zip) might be useful resources here, although none of them do 3D

**Comment by sampoder** [comment]
https://github.com/hackclub/site/pull/1108
