### ISSUE TITLE
front page on community (aka slack) has some grammar issues + let's add that it's for TEENS

### ISSUE THREAD

**Issue by karamassie** [hackclub/site#1113]
just the top line pls edit. the ama line is fine!

Coding doesn’t have to be a solitary activity. At Hack Club, we make remarkable things together, and in our Slack you’ll find awesome people to hang out with too. Code together, find your programming community, dream up something wild, or just #lounge.

**Comment by Chay2203** [comment]
Hey, I can solve this issue, can you please assign this to me :)

**Comment by Chay2203** [comment]
Can you explain to me more, about where to make the changes? @karamassie

**Comment by karamassie** [comment]
https://hackclub.com/
"our online community"

**Comment by owais-21** [comment]
Can i fix this?

**Comment by opticaldrive** [comment]
I'm guessing that this issue should be closed - the PR wasn't marked to close it, but it does resolve the issue.
