### ISSUE TITLE
Update the /stickers page!

### ISSUE THREAD

**Issue by maxwofford** [hackclub/site#1154]
![surfius](https://github.com/hackclub/site/assets/5891442/cf40055d-0a11-423d-985e-2df42339aeec)

**Comment by maxwofford** [comment]
More stickers on the way!

![16332315_working](https://github.com/hackclub/site/assets/5891442/cd33d9f5-4197-4226-b571-9300caaac81c)
![16332318_working](https://github.com/hackclub/site/assets/5891442/fee29d2b-8425-4e43-b4d7-9e6c32d0d924)
![16332316_working](https://github.com/hackclub/site/assets/5891442/b7c6f1f1-ed5e-4f34-9eb2-4b7da6e021a9)
![16161013_working(1)](https://github.com/hackclub/site/assets/5891442/bf0f1b9c-35d7-452f-b2a5-bd7433d47a3c)
![1R](https://github.com/hackclub/site/assets/5891442/be6ac0e8-078d-40d7-a7dc-05de4d3a11bd)
![Untitled-3(1)](https://github.com/hackclub/site/assets/5891442/bbf27294-27b8-47b6-87ef-af0dcd5ef711)
![boba_sticker](https://github.com/hackclub/site/assets/5891442/4e98dba8-ee01-4eda-b36e-4107b7fc6bb8)
![0rummaging](https://github.com/hackclub/site/assets/5891442/e5201501-c215-4dd5-8957-0ec6bc637257)
![0frame_1__50_](https://github.com/hackclub/site/assets/5891442/e04d946b-d3fd-48fa-9a1d-86ae5b903b36)
![1prototype](https://github.com/hackclub/site/assets/5891442/8f4a9628-456b-42a0-9d0b-2b7b94532e49)

**Comment by cytronicoder** [comment]
omg I want these please

**Comment by DevSrijit** [comment]
@maxwofford can we close this issue now ?

**Comment by maxwofford** [comment]
Closed by https://github.com/hackclub/site/pull/1181
