### ISSUE TITLE
"Limited" -> "Only X left"

### ISSUE THREAD

**Issue by maxwofford** [hackclub/site#1245]
Currently the shop doesn't make it clear that there's limited quantity for items. It'd be nice to actually list this and mention the total number of the items

**Comment by maxwofford** [comment]
<img width="245" alt="Screenshot 2024-06-21 at 11 22 52" src="https://github.com/hackclub/site/assets/5891442/39bd06cd-ad79-48d2-8844-3b6d9124664a">

This is the field in Airtable

**Comment by Sidd-underscore** [comment]
I'll get started on this!
