### ISSUE TITLE
Clearer purchasable / not purchasable items in shop

### ISSUE THREAD

**Issue by maxwofford** [hackclub/site#1253]
Change background color for items not purchasable

<img width="699" alt="Screenshot 2024-06-21 at 15 59 47" src="https://github.com/hackclub/site/assets/5891442/d65b8eb0-ae7d-4d0b-a664-01df5c7ca405">

**Comment by ankur-kalita** [comment]
hey @maxwofford I want to work on this issue, can you assign it to me

**Comment by Aryankpoor** [comment]
Would be a good idea to close this issue since arcade has ended.
