### ISSUE TITLE
Shop labels overlapping

### ISSUE THREAD

**Issue by maxwofford** [hackclub/site#1265]
<img width="770" alt="Screenshot 2024-07-01 at 16 05 20" src="https://github.com/hackclub/site/assets/5891442/d72c95af-428f-40a9-a84a-580ddff6a2f0">

**Comment by emergenitro** [comment]
Unfortunately the only fix that comes to mind is making the "Only {stock} left!" ones into `-${ticketRotation}deg` which makes it look like this:
![image](https://github.com/hackclub/site/assets/49610482/ec1d568a-013d-4d88-b283-cc2c947adf6d)

I can make that change but if there's anything else which you can suggest, do assign me and I'll change it.

**Comment by Harshinireddy05** [comment]
can I work on this issue?

**Comment by Aryankpoor** [comment]
This issue seems to be already resolved. Time to close this maybe?

**Comment by maxwofford** [comment]
In that can I'm closing this!
