### ISSUE TITLE
[Team page] Add Caleb, Deet, and Thomas to Acknowledgements section

### ISSUE THREAD

**Issue by garyhtou** [hackclub/site#1298]
@cjdenio, @Deetschoe, and @SerenityUX have helped shape Hack Club into what it is today! Let's add/move them to the acknowledgments section of the team page.

```[tasklist]
### Tasks
- [ ] Add @cjdenio
- [ ] Add @Deetschoe 
- [ ] Add @SerenityUX 
```

**Comment by taciturnaxolotl** [comment]
I can do this!

**Comment by taciturnaxolotl** [comment]
Can we get a merge on this? i want to get some cookies and chai!
