### ISSUE TITLE
Able to buy multiple OpenAI Credits with just 3 Tickets

### ISSUE THREAD

**Issue by ghost** [hackclub/site#1307]
Once a person buys OpenAI, credits and clicks Buy Now, and returns back to the same page and clicks Buy Now again.
An order is being fulfilled without deduction of tickets.

![Screenshot 2024-08-13 at 5 20 18 PM](https://github.com/user-attachments/assets/43f7b732-0617-4323-989a-4a8c7b2383d1)

**Comment by YodaLightsabr** [comment]
Hi there! I'm having trouble reproducing this, could you provide me with some more detailed steps?

**Comment by ghost** [comment]
Just click Place Order and Instantly clikc back, and you will come to the same page and you will be able to buy tickets again.
