### ISSUE TITLE
The Bin image icon is not transparent

### ISSUE THREAD

**Issue by FinnE145** [hackclub/site#1309]
![image](https://github.com/user-attachments/assets/d1ac6ddc-1083-404a-981d-4d7b3e203b13)
In the auto-scrolling carousel of different hack club projects, the icon for The Bin is not transparent (probably because its a GIF), so it has black corners.

**Comment by matytyma** [comment]
> probably because it's a GIF
GIFs can be transparent too, they were actually one the first image types supporting transparency

**Comment by FinnE145** [comment]
> > probably because it's a GIF\
> GIFs can be transparent too, they were actually one the first image types supporting transparency

could be that whatever software was used to mask it into a circle does not support transparency, or was not configured to use it

**Comment by matytyma** [comment]
Yeah, that could
