### ISSUE TITLE
Trail section says "join us" on homepage

### ISSUE THREAD

**Issue by opticaldrive** [hackclub/site#1373]
<img width="1160" alt="Screenshot 2024-09-14 at 4 03 51 PM" src="https://github.com/user-attachments/assets/cc1ccf68-d0fe-4307-9172-f1e2db179f85">
Trail section says "join us" on homepage
Probably should be changed, as the trail has been trailed. 
Thanks.

**Comment by Aryankpoor** [comment]
Maybe we should change it to `View the documentry` which links to the trail documentry on the youtube channel

**Comment by opticaldrive** [comment]
That's a good idea.
If you don't want to make a PR, I'll do it.

**Comment by Aryankpoor** [comment]
I will go ahead and add that

**Comment by opticaldrive** [comment]
Thanks, do tag the issue in the PR.

**Comment by Monoverde888** [comment]
i think the trail website is on another repo, [hackclub/the-trail](https://github.com/hackclub/the-trail)

**Comment by Monoverde888** [comment]
ooh just noticed it’s about the card on the home
