### ISSUE TITLE
Count To a Million current counter broken

### ISSUE THREAD

**Issue by opticaldrive** [hackclub/site#1388]
Count To a Million current counter broken
Homepage,
<img width="172" alt="Screenshot 2024-09-24 at 10 10 16 AM" src="https://github.com/user-attachments/assets/139917d8-fcdb-4d88-9050-2f29fea71dd6">

**Comment by taciturnaxolotl** [comment]
on it 🫡

**Comment by abc-is-here** [comment]
The whole bot is broke actually, also jia stopped working and drac gives wrong average all the time.
Thank you for fixing it!

**Comment by opticaldrive** [comment]
aah, @kcoderhtml also told me that.
Thanks!
