### ISSUE TITLE
[HCB] Updated copy for HCB application

### ISSUE THREAD

**Issue by garyhtou** [hackclub/site#1394]
We want to update the copy for the HCB application to help get a better understanding of adult orgs that are applying and to give them a more realistic timeline.

From @dwahbe:
```
Add question text: Is your organization led by teenagers? Y/N
Description text: This means your organization was founded and is being led exclusively by teenagers.
If no, additional questions for adults are:
- Question text: Please describe any political activity your organization is involved in. Text box
- Description text: This includes but is not limited to protests, public demonstrations, political education, and lobbying.
- What is your estimated annual budget for this year? Text box
- The ending card says we will get back to you within two weeks. (if you're an adult. If you're a teenager, then the card stays the same)
```

**Comment by garyhtou** [comment]
To make this happen, you'll likely need to add some new fields to Airtable.

**Comment by AQIB-NAWAB** [comment]
Hy @garyhtou ,
can you bit explain more where do you want to add these fields ?
is in the under this link https://hackclub.com/fiscal-sponsorship/apply/ ?
Thanks

**Comment by garyhtou** [comment]
Hi @AQIB-NAWAB, yes! This would be https://hackclub.com/fiscal-sponsorship/apply/

I should have also clarified that I was planning on having someone internal to the HCB team handle this ticket since it requires access to our Airtable to add the fields. Thank you for offering to help though!
