### ISSUE TITLE
Chrome autofill on /bank breaks styling of form

### ISSUE THREAD

**Issue by zachlatta** [hackclub/site#198]
@summerplaybook was going through the application flow on /bank and ran into the below issue. Steps below to reproduce:

1. Go to https://hackclub.com/bank/ in Chrome

2. Scroll to bottom and allow Chrome to autofill your name and address

3. Notice that the text is pure black (see screenshot below)

![image](https://user-images.githubusercontent.com/992248/132583659-f154944f-c0bc-4292-9bb2-8f03e78623fd.png)

(what it should look like)

![image](https://user-images.githubusercontent.com/992248/132583704-89ae6a2d-02d3-465c-870b-1cb7b74a017b.png)

---

We should fix the styling so text that is autofilled by Chrome looks the same as text that you type yourself.

**Comment by exu3** [comment]
Nice catch, thanks! #199 should fix it
