### ISSUE TITLE
HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

### ISSUE THREAD

**Issue by ibnz36** [hackclub/site#235]
Error thrown when trying to send a request to https://hackclub.com/api/join.

**Comment by sampoder** [comment]
That's weird, is this happening multiple times? And is this happening in the browser or from manually making a request?

**Comment by ibnz36** [comment]
Both with curl and the browser. I tried it multiple times

**Comment by sampoder** [comment]
Can't reproduce, closing
