### ISSUE TITLE
Navbar not rendering in development

### ISSUE THREAD

**Issue by exu3** [hackclub/site#306]
In development, the navbar doesn't show up for some reason.
Was able to reproduce this issue locally, in a Codespaces environment and seems like #305 had a similar issue.

<img width="1503" alt="Screen Shot 2022-01-19 at 4 10 16 PM" src="https://user-images.githubusercontent.com/72365100/150238644-92812a1f-633e-4b43-bc0e-b831fa9f1811.png">

**Comment by cjdenio** [comment]
I'm getting the same exception, but the navbar still works (in both Firefox and Safari)

<img width="1776" alt="Screen Shot 2022-01-19 at 7 23 29 PM" src="https://user-images.githubusercontent.com/34525547/150239786-54c556b6-88a9-4ec7-ab07-cf942cd77d40.png">

**Comment by exu3** [comment]
<img src="https://emoji.slack-edge.com/T0266FRGM/thinking/b6498e11966b2a96.png" width="20"> The navbar isn't working for me in Chrome, Firefox, or Safari. I wonder what the issue could be.

**Comment by cjdenio** [comment]
Perhaps it's related to this error:
<img width="900" alt="Screen Shot 2022-01-19 at 7 40 39 PM" src="https://user-images.githubusercontent.com/34525547/150241330-0095af85-da10-4292-a910-2ce514f2eaa0.png">
<img src="https://emoji.slack-edge.com/T0266FRGM/aaa-dino/241d61607bebf143.png" width="25" />
