### ISSUE TITLE
Slack signup disable feature

### ISSUE THREAD

**Issue by maxwofford** [hackclub/site#352]
We've had to occasionally lock down our slack signup form and API when someone tweets about us (most recently [Vitalik](https://twitter.com/VitalikButerin/status/1489409521806020611)).

In the past these have been kinda last-second and could be so much better (see https://github.com/hackclub/site/pull/338).
<img width="1240" alt="Screen Shot 2022-02-07 at 09 58 39" src="https://user-images.githubusercontent.com/5891442/152813300-e0800994-979a-4953-8170-53067faed05a.png">

It'd be cool to have a nice looking waitlist form that can be enabled that explains our signups are temporarily locked down but a user can fill out the form to join the waitlist, and we'll review applications in a couple days.

**Comment by sampoder** [comment]
Waitlist functionality basically already exists, we just need remove the code that invites people in the API function and move it into a Airtable automation
