### ISSUE TITLE
Add Bank logos to https://hackclub.com/brand/

### ISSUE THREAD

**Issue by zachlatta** [hackclub/site#401]
https://hackclub.com/brand/ is super helpful and has downloadable logos for Hack Club. It would be awesome if Hack Club Bank's logos  were downloadable from the page too!

**Comment by zachlatta** [comment]
[Hack Club Bank branding.zip](https://github.com/hackclub/site/files/8397421/Hack.Club.Bank.branding.zip)
[Hack Club Bank branding (1).zip](https://github.com/hackclub/site/files/8397425/Hack.Club.Bank.branding.1.zip)

Here are the light mode and dark mode logos for Bank.

**Comment by cjdenio** [comment]
Would this replace https://bank.hackclub.com/branding?

**Comment by zachlatta** [comment]
Oh hmm. I didn't know about that page. What if we made that https://bank.hackclub.com/brand/ instead of /branding/ and then have a prominent link from https://hackclub.com/brand/ to https://bank.hackclub.com/brand/?
