### ISSUE TITLE
New signup form for Slack

### ISSUE THREAD

**Issue by maxwofford** [hackclub/site#410]
I'm working on a new version of the clippy flow (~https://github.com/hackclub/clippy/pull/45~ EDIT: https://github.com/hackclub/toriel/pull/1) & as part of it I need to get more info than the current slack signup form gives. The new form should include:

- email
- ip
- continent
- teen or not (boolean)
	- if not, let's flash a warning/info about this mostly being teens
- in highschool or not
- why you want to join

EDIT: It should also send a POST request to https://toriel.hackclub.com/slack_invite with a TORIEL_KEY.

**Comment by sampoder** [comment]
ip
continent

can we pull these from the request instead of manual input?

**Comment by sampoder** [comment]
teen or not (boolean)
if not, let's flash a warning/info about this mostly being teens
in highschool or not

can these be combined? feels a bit tedious

**Comment by maxwofford** [comment]
> can we pull these from the request instead of manual input?

I think it makes sense to have IP automatic, but maybe that can prefill the continent? I'd like to still give people the chance to choose in case IP matching gets the wrong area.

**Comment by maxwofford** [comment]
> can these be combined? feels a bit tedious

Yeah, probably! I think the only constraint here is that APAC has 1 flow for high schoolers and 1 flow for colleges, but we can figure that out from high school or not

**Comment by maxwofford** [comment]
Auth details can be found on heroku (app is `toriel-hackclub`)! https://github.com/hackclub/toriel/commit/b7678048fa3da2a3c097603224cf5a913ebb685d
