### ISSUE TITLE
Autofill continent from IP

### ISSUE THREAD

**Issue by maxwofford** [hackclub/site#412]
It'd be awesome to autofill this from where the user connects from. Let's keep the dropdown b/c ip geocoding is inaccurate, but a nice touch while filling out a form.

<img width="753" alt="Screen Shot 2022-04-07 at 16 33 02" src="https://user-images.githubusercontent.com/5891442/162291122-1ecaa7bb-cb5c-49da-bcda-65678cfc1568.png">

**Comment by idanzhavi09** [comment]
HI, id like to work on this

**Comment by maxwofford** [comment]
Thanks for the help @idanzhavi09! I appreciate it.

**Comment by sampoder** [comment]
For this I'd recommend using Middleware

**Comment by cjdenio** [comment]
I think plain ol' server-side rendering should work fine for this
