### ISSUE TITLE
Visible `continent` query parameter on `hackclub.com/slack`

### ISSUE THREAD

**Issue by cjdenio** [hackclub/site#436]
<img width="469" alt="Screen Shot 2022-04-25 at 12 46 32 PM" src="https://user-images.githubusercontent.com/34525547/165135456-7840a317-5c67-4f58-91c8-2893b819b4e7.png">

While this is technically expected behavior, it's a little... odd. Ideally it wouldn't be visible. Just a thought.

**Comment by sampoder** [comment]
this oddity has been fixed! we're now using cookies, check it out:

<img width="934" alt="Screenshot 2023-08-15 at 1 11 56 PM" src="https://github.com/hackclub/site/assets/39828164/bdd07ee3-de2c-467b-92b6-9f1350020c3a">
