### ISSUE TITLE
Fix "Live from our Slack"

### ISSUE THREAD

**Issue by cjdenio** [hackclub/site#437]
<img width="212" alt="Screen Shot 2022-04-25 at 12 54 32 PM" src="https://user-images.githubusercontent.com/34525547/165136765-e1a685c1-da80-4547-879f-f2e5e9fefb13.png">

#sleep doesn't even exist

**Comment by maxwofford** [comment]
I'd absolutely _love_ for us to make this a real endpoint again. Anyone up for taking that on as a project?

**Comment by cjdenio** [comment]
I can work on that this week!

**Comment by sampoder** [comment]
#sleep is my favourite channel

**Comment by YodaLightsabr** [comment]
@tejasag made a really cool bot that shares which channel you're typing in, and it's entirely opt-in. It might be possible to integrate it with the Live from our Slack?

**Comment by warrenyun** [comment]
this seems like a pretty cool idea, is tejas still open to possibly making this work? i'd love to give it a shot!

**Comment by cfanoulis** [comment]
@cjdenio hey did u end up working on a streambot replacement?
