### ISSUE TITLE
Adding Hack Club "Clubs" Video Onto website

### ISSUE THREAD

**Issue by abbyfischler** [hackclub/site#527]
<img width="306" alt="Screen Shot 2022-08-24 at 11 55 50 AM" src="https://user-images.githubusercontent.com/46800781/186500444-139554af-018a-49d5-99f9-4ffaaacf9718.png">

https://youtu.be/-sxRdKtKNa0

**Comment by sampoder** [comment]
Let's keep in this in mind for future refreshes, however, there isn't an easy space to drop it in right now.
