### ISSUE TITLE
Add More Stickers!

### ISSUE THREAD

**Issue by sampoder** [hackclub/site#528]
- [x] Assemble Logo Sticker
- [x] Hackers, assemble!
- [x] Bank Card
- [x] Bank Long Sticker (Light Mode)
- [x] Bank Long Sticker (Dark Mode)
- [x] Bank Logo (Dark Mode)
- [x] Hack Club Design Awards Sticker
- [x] Sprig Orpheus
- [x] Sprig Sticker Sheet
- [x] Zephyr Sticker
- [x] Orpheus sledding

These are just the ones that I remember, there are probably a bunch more. The Sprig ones might not be final.

**Comment by IamTregsthedev** [comment]
where is this for?

**Comment by radioblahaj** [comment]
I can add thesse if someone gives me the files for all of the stickers

**Comment by maggie-j-liu** [comment]
~~sinerider stickers!~~ oops they're already there

what about the orpheus holding duck sticker?

**Comment by exu3** [comment]
Sprig stickers aren't finalized yet, but we should definitely add them once they've been finalized and ordered.

**Comment by exu3** [comment]
cc @bellesea for the Sprig sticker sheets

**Comment by exu3** [comment]
![Frame 50](https://user-images.githubusercontent.com/72365100/209169073-efbf2088-cd11-404c-acca-9138cbeb60f7.png)
![Frame 49](https://user-images.githubusercontent.com/72365100/209169075-d8e99e4d-f1fc-4695-b883-3d861eec28c9.png)
![Frame 53](https://user-images.githubusercontent.com/72365100/209169076-130b5204-9ea1-4d43-b40e-8b7a4901b424.png)
![Frame 51](https://user-images.githubusercontent.com/72365100/209169079-516097e1-7f3a-4a59-95d8-6bb02f5f2ffe.png)


Here are the Sprig sticker sheets. I'm not sure they fit on this page as the only way to get them is to make a Sprig game, and the intended use for them is to decorate your Sprig case.
