### ISSUE TITLE
Application Email address validation 

### ISSUE THREAD

**Issue by ttjerry** [hackclub/site#532]
Looks like from the first time you input a wrong email address even when corrected there is still this pop up saying the address does not exist
I had to refresh the page and included"WWW." before my email address

**Comment by sampoder** [comment]
Hey @Jerryking18! Sorry about this :/ Could you send a screen recording of the bug?

**Comment by ttjerry** [comment]
https://user-images.githubusercontent.com/90741117/188532350-29816203-eff0-40d4-a0ce-f08f60dcef9a.mp4

Here

**Comment by sampoder** [comment]
<img width="313" alt="Screenshot 2022-09-06 at 12 32 36 PM" src="https://user-images.githubusercontent.com/39828164/188547486-e3012429-ce7b-4a7b-adff-b72e388bb7e4.png">

Could you try removing this space?

**Comment by ttjerry** [comment]
Okay thanks for that
