### ISSUE TITLE
Winter Demo accounts should be flagged as winter accounts

### ISSUE THREAD

**Issue by maxwofford** [hackclub/site#653]
<img width="1261" alt="Screenshot 2022-12-20 at 13 25 12" src="https://user-images.githubusercontent.com/5891442/208739545-a60cb513-bd60-49af-b30e-46b6e4b33fd6.png">

Currently this signup form doesn't register demo accounts as winter hardware grant accounts.

**Comment by cfanoulis** [comment]
(winter grant accounts are different than usual bank accounts?)

**Comment by exu3** [comment]
> (winter grant accounts are different than usual bank accounts?)

The `category` field is different.

**Comment by maxwofford** [comment]
@cfanoulis The `category` field isn't user-facing, it just helps our ops team sort accounts by filtering for things like:

- high school hackathon
- adult nonprofit
- winter hardware grants

It doesn't affect anything for the user of the account.

**Comment by cjdenio** [comment]
[oop](https://github.com/hackclub/site/pull/654)
