### ISSUE TITLE
Upcoming Hackathons Text Bug

### ISSUE THREAD

**Issue by alexdevz** [hackclub/site#659]
![image](https://user-images.githubusercontent.com/38901010/209892581-1b7f98cd-cb44-4d71-8625-9374ba7e8a5f.png)
It displays the current month (i presume) or just December instead of the actual month of the upcoming hackathons in the list. It is still correct on the hackathons site.

**Comment by exu3** [comment]
Good catch! It should have been fixed by 2194b33730ae1c17cd2816ec127bfe6cce613d89 / 77fcd834b7b647c6ad5a25a76741d2c542604732
