### ISSUE TITLE
Use `react-fast-marquee`

### ISSUE THREAD

**Issue by exu3** [hackclub/site#668]
<img width="372" alt="Screenshot 2023-01-04 at 6 20 25 PM" src="https://user-images.githubusercontent.com/72365100/210668324-c60d9676-418f-42b1-a1a0-5dac72fd06ae.png">

Related to #666

**Comment by cfanoulis** [comment]
Apparently this pkg doesn't work with nextjs

the search continues; meanwhile pls close

**Comment by aramshiva** [comment]
This Package works with Next.js! I can verify, I used it with [Hack The Sound](https://hackthesound.net/#:~:text=sponsors)
