### ISSUE TITLE
New Sprig games aren't rendering correctly on the homepage

### ISSUE THREAD

**Issue by ajsirota** [hackclub/site#832]
![image](https://github.com/hackclub/site/assets/67526318/e8dc6467-848e-47e4-b4ee-6f14e038b31e)

**Comment by bellesea** [comment]
ack thank you for logging this! would you be interested in taking a stab at fixing this? 

relevant code
https://github.com/hackclub/site/blob/main/pages/api/games.js
https://github.com/hackclub/site/blob/main/components/index/cards/sprig.js

**Comment by malted** [comment]
Fixed!

**Comment by malted** [comment]
I fixed it through 5d447ce and 255c446
