### ISSUE TITLE
UI of the Footer 

### ISSUE THREAD

**Issue by SiddharthaMishra-dev** [hackclub/site#841]
In the working site, Links in the footer navigation doesn't; have any animation or styling that can help user to navigate the link with easy.
I can add styling.

**Comment by SiddharthaMishra-dev** [comment]
> In the working site, Links in the footer navigation doesn't; have any animation or styling that can help user to navigate the link with easy. I can add styling.

@motdotla @conradev @jessicard @zfogg

**Comment by sampoder** [comment]
Thanks for flagging this @SiddharthaMishra-dev! I've added an underline on hover to make it clearer, feel free to PR in any additional modifications you think we should make.
