### ISSUE TITLE
Team page has broken icons

### ISSUE THREAD

**Issue by grymmy** [hackclub/site#929]
Extra credit for fixing this in a way that makes broken icons not look so broken in the future.

See img:
<img width="256" alt="Screenshot 2023-09-20 at 8 49 02 PM" src="https://github.com/hackclub/site/assets/43505167/57d72546-ab76-4daa-b0d8-6ec1349474f3">

Note that maggie, gaurav, and hugo have broken icons that look super wonk.

**Comment by tobyab** [comment]
Just made a PR fixing this! #930. What does the review process look like?

**Comment by grymmy** [comment]
I prefer ppl self-merging after receiving at least 1 approval.  When I get back to me desk, I will add you as a hackclub/site contributor.

**Comment by tobyab** [comment]
Fixed in #930!
